### ISSUE TITLE
2 possible package resolutions

### ISSUE THREAD

**Issue by juanfcocontreras** [conda-forge/arosics-feedstock#26]
Since the last update, I have the following message:

```
Collecting package metadata (current_repodata.json): done
Solving environment: |
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-forge/noarch::folium-0.11.0-py_0, conda-forge/osx-64::arosics-1.2.5-py38h50d1736_0
  - conda-forge/noarch::folium-0.12.0-pyhd8ed1ab_0, conda-forge/noarch::arosics-0.9.24-pyh9f0ad1d_0
```

I think this is solved in the pip version changing the requirement `folium>=0.6.0,!=0.12.0` by `folium>=0.6.0`, but not in the conda-forge version, am I right?

Thanks!

**Comment by danschef** [comment]
Actually, this should be solved in the latest release (v1.2.5):

https://github.com/conda-forge/arosics-feedstock/blob/e36db03171580898ca2d9776e67b00cfa0a30189/recipe/meta.yaml#L27

Could you try to force conda to install arosics 1.2.5 by running `conda install -c conda-forge arosics=1.2.5`. I am not sure why conda´s package resolver suggests v0.9.24 at all (@ocefpaf do you see a chance to avoid this?).

Unfortunaly, there was a broken folium release (0.12.0), which was already patched on PyPI (0.12.1) but the 0.12.1 release is still missing on conda-forge (see https://github.com/python-visualization/folium/issues/1438). So the only way I see to work around this at the moment is to block folium 0.12.0 and to fall back to 0.11.0 in arosics.

**Comment by juanfcocontreras** [comment]
I can do that, but everytime I do:

```
conda update --all
```

I get the same message. I didn't know about the broken folium release. I hope they can fix it soon.

Thanks!

**Comment by juanfcocontreras** [comment]
I think resolver suggests v0.9.24 because if I have installed folium 0.12.0, it is the latest arosics version compatible (it doesn't have an explicit folium!=0.12.0)

I think everything will be solve with the new folium release.

Please, close this issue if your are fine with that.

**Comment by danschef** [comment]
The latest compatible version should be 1.2.3 because this does not block folium 0.12.0. Version 0.9.24 was simply the last noarch release but it is outdated now and should not suggested by the resolver anymore.

However, I guess `conda update --all` should work if you would create a completely new environment with `conda env create -n arosics_env -c conda-forge arosics`.

**Comment by ocefpaf** [comment]
Note that this is legit and not an error. The warning is just letting you know that the solver found two possible solutions and is choosing one. If you want the other solution then you'll need to pin things to make it easier for the solver to find only that one.

**Comment by danschef** [comment]
The thing is that the solver found two versions of my own package. The latest one (1.2.5) and a completely outdated one (0.9.24). The only reason for this behaviour that I can image is that 0.9.24 is the latest noarch version. Later releases are architecture specific. But I cannot pin my own package. I just want to avoid that the solver suggests such outdated versions.

**Comment by danschef** [comment]
This seems to be fixed after updating some package metadata of the older conda-forge arosics releases [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/138). Closing this for now.
